SELECT TOP (1000) [UserId]
      ,[FirstName]
      ,[LastName]
      ,[Username]
      ,[Email]
      ,[Password]
      ,[CreatedAt]
      ,[UpdatedAt]
      ,[ProfilePic]
      ,[CoverPhoto]
  FROM [dbo].[User]
